#!/bin/bash 

DALI=""
SRC=""

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --src) SRC="$(cd "$2" && pwd)"; shift ;;
        --dali) DALI="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

echo "SRC: $SRC"
echo "DALI: $DALI"

if ! docker info &> /dev/null; then
  echo "Docker is not running. Please start Docker Desktop and wait for it to be ready."
  exit 1
fi

docker system prune -f 
docker container prune -f 
docker image prune -f 
src=$SRC dali=$DALI docker compose down --remove-orphans
src=$SRC dali=$DALI docker compose up -d --build --force-recreate --no-deps
src=$SRC dali=$DALI docker compose logs -f