#!/bin/bash 

#!/bin/bash

#!/bin/bash

# Default values
SICSTUS=""
SRC=""
DALI=""

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --sicstus) SICSTUS="$2"; shift ;;
        --src) SRC="$2"; shift ;;
        --dali) DALI="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

echo "SICSTUS: $SICSTUS"
echo "SRC: $SRC"
echo "DALI: $DALI"


if ! command -v docker &> /dev/null; then
  echo "install docker engine following the instructions at https://docs.docker.com/engine/install/"
  exit 1
fi

docker system prune -f 
docker container prune -f 
docker image prune -f 
sicstus=$SICSTUS src=$SRC dali=$DALI docker compose down --remove-orphans
sicstus=$SICSTUS src=$SRC dali=$DALI docker compose up -d --build --force-recreate
sicstus=$SICSTUS src=$SRC dali=$DALI docker compose logs -f