#!/bin/bash 

if ! command -v docker &> /dev/null; then
  echo "install docker engine following the instructions at https://docs.docker.com/engine/install/"
  exit 1
fi

docker system prune -f 
docker container prune -f 
docker image prune -f 
docker compose down --remove-orphans
docker compose up -d --build --force-recreate
docker compose logs -f